# Generated by Django 3.1.7 on 2021-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210227_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Go and Read', max_length=255),
        ),
    ]
