# Generated by Django 3.1.7 on 2021-02-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210227_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='web_page',
        ),
    ]
